CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    organization_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE IF NOT EXISTS checklists (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    frequency VARCHAR(50),
    module VARCHAR(50),
    organization_id BIGINT,
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE IF NOT EXISTS checklist_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP,
    completed_by BIGINT,
    checklist_id BIGINT,
    FOREIGN KEY (completed_by) REFERENCES users(id),
    FOREIGN KEY (checklist_id) REFERENCES checklists(id)
);

CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    min_temp DOUBLE NOT NULL,
    max_temp DOUBLE NOT NULL,
    organization_id BIGINT,
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE IF NOT EXISTS temperature_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reading_value DOUBLE NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    is_deviation BOOLEAN DEFAULT FALSE,
    equipment_id BIGINT,
    logged_by BIGINT,
    FOREIGN KEY (equipment_id) REFERENCES equipment(id),
    FOREIGN KEY (logged_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS deviations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    module VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    reported_by BIGINT,
    organization_id BIGINT,
    FOREIGN KEY (reported_by) REFERENCES users(id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
    );

CREATE TABLE IF NOT EXISTS alcohol_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    recorded_at TIMESTAMP NOT NULL,
    shift_date DATE NOT NULL,
    guest_age INT,
    alcohol_percentage DOUBLE,
    id_checked BOOLEAN,
    service_denied BOOLEAN,
    recorded_by BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    FOREIGN KEY (recorded_by) REFERENCES users(id),
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE training_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    content CLOB NOT NULL,
    type VARCHAR(50) NOT NULL,
    completion_type VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    file_name VARCHAR(255),
    file_path VARCHAR(1000),
    CONSTRAINT fk_training_documents_organization
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE training_quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    question VARCHAR(1000) NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(1) NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_training_quiz_document
        FOREIGN KEY (document_id) REFERENCES training_documents(id)
);

CREATE TABLE training_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    passed BOOLEAN NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_training_attempt_document
        FOREIGN KEY (document_id) REFERENCES training_documents(id),
    CONSTRAINT fk_training_attempt_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    issued_at TIMESTAMP,
    CONSTRAINT fk_certification_document
        FOREIGN KEY (document_id) REFERENCES training_documents(id),
    CONSTRAINT fk_certification_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_certification_organization
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE document_acknowledgements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    acknowledged BOOLEAN NOT NULL,
    acknowledged_at TIMESTAMP,
    CONSTRAINT fk_ack_document FOREIGN KEY (document_id) REFERENCES training_documents(id),
    CONSTRAINT fk_ack_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE practical_training_signoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    approved_by_id BIGINT NOT NULL,
    note VARCHAR(1000),
    approved BOOLEAN NOT NULL,
    approved_at TIMESTAMP,
    CONSTRAINT fk_signoff_document FOREIGN KEY (document_id) REFERENCES training_documents(id),
    CONSTRAINT fk_signoff_employee FOREIGN KEY (employee_id) REFERENCES users(id),
    CONSTRAINT fk_signoff_manager FOREIGN KEY (approved_by_id) REFERENCES users(id)
);