import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

/**
 * Pinia store for a simple counter.
 *
 * This is a scaffold store generated by the Vite Vue template.
 * It is not used in the core application logic of Checkd.
 *
 * @store counter
 */
export const useCounterStore = defineStore('counter', () => {
  /** @type {import('vue').Ref<number>} The current count value. */
  const count = ref(0)

  /**
   * A computed value equal to double the current count.
   *
   * @type {import('vue').ComputedRef<number>}
   */
  const doubleCount = computed(() => count.value * 2)

  /**
   * Increments the count by 1.
   */
  function increment() {
    count.value++
  }

  return { count, doubleCount, increment }
})
